Design task/task 2 updated
Team-Imagine-ReImagined/kjourney pull request #24
Opened 2019-11-12 14:56 UTC by Conormc98

2019-11-12 14:59 UTC, JamesMatchett requested changes

2019-11-12 14:59 UTC, JamesMatchett commented on ExpressAPI/index.js
> +app.use(jwt({ secret: process.env.JWT_Secret}).unless({path: ['/login', '/SecureGenerateUser', '/getBandRoles/4']}));
```suggestion
app.use(jwt({ secret: process.env.JWT_Secret}).unless({path: ['/login', '/SecureGenerateUser']}));
```

2019-11-12 14:59 UTC, JamesMatchett commented on ExpressAPI/index.js
> +app.use(jwt({ secret: process.env.JWT_Secret}).unless({path: ['/login', '/SecureGenerateUser', '/getBandRoles/4']}));
Remove getBand from exclusion list

2019-11-12 15:16 UTC, ChrisThompsonK approved these changes
These changes look good to me 👍

2019-11-12 15:26 UTC, JamesMatchett approved these changes

2019-11-13 11:57 UTC, micalexis requested changes
address comments

2019-11-13 11:57 UTC, micalexis commented on ExpressAPI/index.js
>  app.get('/IsUserValid', function(req,res){
refactor your endpoints to make them RESTful

2019-11-13 11:57 UTC, micalexis commented on kjourney/src/app/bands/bands.component.html
> +  <h1 style="margin-top: 20px; text-align: center;" *ngFor="let band of bands">{{ band.bandName }}</h1>
why is this styling for the template not in the .css for the component?

2019-11-13 11:57 UTC, micalexis commented on kjourney/src/app/bands/bands.component.html
> +  <br>
cant this be achieved with styling?

2019-11-13 16:00 UTC, micalexis requested changes
address comments and squash commits

2019-11-13 16:00 UTC, micalexis commented on ExpressAPI/index.js
>  app.get('/IsUserValid', function(req,res){
?

2019-11-13 16:00 UTC, micalexis commented on kjourney/src/app/bands/bands.component.html
>        <tr class="myRow" id="pop-over" *ngFor="let trainingPerBands of trainingPerBand">
how can you get a plural from a singular?
change the names of the variables to make sense

2019-11-13 16:00 UTC, micalexis commented on kjourney/src/app/data.service.ts
> +    return this.http.get<BandRole[]>('api/roles/' + bandID);
you are getting roles by bandId so you need to use query parameters 

`api/roles/?bandId=`

2019-11-14 12:23 UTC, micalexis approved these changes
squash commits

2019-11-14 12:34 UTC, merged