Data from DB to front end
Team-Imagine-ReImagined/kjourney pull request #6
Opened 2019-11-07 15:19 UTC by ChrisThompsonK

2019-11-07 15:44 UTC, micalexis requested changes
apply changes and squash commits

2019-11-07 15:44 UTC, micalexis commented on ExpressAPI/db.js
> +
unnecessary white space, remove

2019-11-07 15:44 UTC, micalexis commented on ExpressAPI/db.js
> +        /*
remove comment if not required

2019-11-07 15:44 UTC, micalexis commented on kjourney/src/app/bands/bands.component.ts
> +    this.trainingPerBand = await this.data.getTrainingPerBand(1);
change to use Observables not Promises

2019-11-07 15:44 UTC, micalexis commented on kjourney/src/app/data.service.ts
> +  public getTrainingPerBand(bandID): Promise<TrainingPerBand[]> {
change to use Observables not Promises

2019-11-07 16:06 UTC, Conormc98 approved these changes

2019-11-08 11:10 UTC, micalexis approved these changes

2019-11-08 11:12 UTC, merged