Display responsibilities for each band
Team-Imagine-ReImagined/kjourney pull request #7
Opened 2019-11-07 15:20 UTC by jessicamcmillen

2019-11-07 15:27 UTC, JamesMatchett commented on ExpressAPI/db.js
> +                logger.error("getResponsibilities failed with error: " + err)
semi colon

2019-11-07 15:27 UTC, JamesMatchett commented on ExpressAPI/db.js
> +            logger.debug("getResponsibilities succeeded.")
semi colon

2019-11-07 15:27 UTC, JamesMatchett commented on kjourney/src/models/responsibility.ts
> +    respDesc: string
3 semi colons here please, thanks

2019-11-07 15:32 UTC, JamesMatchett approved these changes

2019-11-07 15:48 UTC, micalexis requested changes
squash commits 
address the comments

2019-11-07 15:48 UTC, micalexis commented on ExpressAPI/index.js
> +app.get('/responsibilities', function(req, res) {
what is the point of this route? are you not supposed to be getting responsibilities per band or role? a generic get of all responsibilities seems odd

2019-11-07 15:48 UTC, micalexis commented on kjourney/src/app/app.component.css
> +/* footer {
remove comment if not required

2019-11-07 15:48 UTC, micalexis commented on kjourney/src/app/bands/bands.component.css
> +  /* footer {
same as above

2019-11-07 15:48 UTC, micalexis commented on kjourney/src/app/bands/bands.component.ts
> +    this.data.getResponsibilities().subscribe((r => {
👍 but comment above should be addressed

2019-11-07 15:48 UTC, micalexis commented on kjourney/src/app/main/main.component.css
> +  /* footer {
remove if not required

2019-11-07 16:05 UTC, Conormc98 approved these changes

2019-11-08 11:12 UTC, micalexis approved these changes
make sure you squash the commits before merging!!!!!

2019-11-08 12:03 UTC, Conormc98 approved these changes

2019-11-08 12:03 UTC, Conormc98 commented on ExpressAPI/db.js
> +});
Big important change 😂

2019-11-08 12:05 UTC, e-mccoy approved these changes

2019-11-08 12:12 UTC, merged